name: delimed

services:
  db:
    image: postgres:16-alpine
    container_name: delimed_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysteam2006
      POSTGRES_DB: delimed
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d delimed"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - delimed_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: delimed_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - CONFIG_PATH=/app/config/config.yaml
    volumes:
      - ./config:/app/config:ro
    networks:
      - delimed_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  delimed_network:
    driver: bridge

