env: local #local, dev, prod
jwt_secret: andrey
http_server:
  port: :8080
  write_timeout: 5s
  read_timeout: 5s
  idle_timeout: 60s
database:
  dsn: "host=db port=5432 user=admin password=mysteam2006 dbname=delimed sslmode=disable"
  host: "db"
  port: 5432
  user: "admin"
  password: "mysteam2006"
  name: "delimed"
  sslmode: "disable" 
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: "1h"
  conn_max_idle_time: "30m"
cdek:
  client_id: wqGwiQx0gg8mLtiEKsUinjVSICCjtTEP
  client_secret: RmAmgvSgSl1yirlz9QupbzOJVqhCxcP5
  login: wqGwiQx0gg8mLtiEKsUinjVSICCjtTEP
  password: RmAmgvSgSl1yirlz9QupbzOJVqhCxcP5
dellin:
  app_key: "1E211F21-EE54-4EE4-B33E-F889DC83383F" # TODO: добавить app_key для API Деловых Линий